### ISSUE TITLE
Installation fails on windows 

### ISSUE THREAD

**Issue by tobsecret** [jasongrout/jupyterlab-fasta#5]
Here is the stack trace:
```
$ jupyter labextension install ./jupyterlab-fasta
> npm pack C:\Users\Tobias\Documents\Docs\Clubs\Conferences\2017_July_Scipy\Tutorials\jupyterlab-fasta
'npm' is not recognized as an internal or external command,
operable program or batch file.

Traceback (most recent call last):
  File "C:\Users\Tobias\Miniconda3\envs\PDSH_mod\Scripts\jupyter-labextension-script.py", line 5, in <module>
    sys.exit(jupyterlab.labextensions.main())
  File "C:\Users\Tobias\Miniconda3\envs\PDSH_mod\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\Tobias\Miniconda3\envs\PDSH_mod\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\Tobias\Miniconda3\envs\PDSH_mod\lib\site-packages\jupyterlab\labextensions.py", line 167, in start
    super(LabExtensionApp, self).start()
  File "C:\Users\Tobias\Miniconda3\envs\PDSH_mod\lib\site-packages\jupyter_core\application.py", line 256, in start
    self.subapp.start()
  File "C:\Users\Tobias\Miniconda3\envs\PDSH_mod\lib\site-packages\jupyterlab\labextensions.py", line 57, in start
    for arg in self.extra_args]
  File "C:\Users\Tobias\Miniconda3\envs\PDSH_mod\lib\site-packages\jupyterlab\labextensions.py", line 57, in <listcomp>
    for arg in self.extra_args]
  File "C:\Users\Tobias\Miniconda3\envs\PDSH_mod\lib\site-packages\jupyterlab\commands.py", line 96, in install_extension
    run(['npm', 'pack', extension], cwd=target, logger=logger)
  File "C:\Users\Tobias\Miniconda3\envs\PDSH_mod\lib\site-packages\jupyterlab\commands.py", line 61, in run
    raise error
  File "C:\Users\Tobias\Miniconda3\envs\PDSH_mod\lib\site-packages\jupyterlab\commands.py", line 57, in run
    return check_output(cmd, **kwargs)
  File "C:\Users\Tobias\Miniconda3\envs\PDSH_mod\lib\subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "C:\Users\Tobias\Miniconda3\envs\PDSH_mod\lib\subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['npm', 'pack', 'C:\\Users\\Tobias\\Documents\\Docs\\Clubs\\Conferences\\2017_July_Scipy\\Tutorials\\jupyterlab-fasta']' returned non-zero exit status 1
```

**Comment by jasongrout** [comment]
This looks like a problem with jupyterlab. Maybe this is related to this patch for finding npm on windows: https://github.com/jupyter-widgets/widget-cookiecutter/pull/21

CC @blink1073

**Comment by blink1073** [comment]
Thanks for the heads up, I'll add this to a PR I just started to clean up build handling.
