### ISSUE TITLE
No right click 'open as fasta' menu

### ISSUE THREAD

**Issue by danpf** [jasongrout/jupyterlab-fasta#7]
Not exactly sure if i'm clicking where i should be... but when I right click on a fasta file in the file browser sidebar I don't see an open as fasta format option.

**Comment by JenCabral** [comment]
Same is happening to me. I've installed this as directed on a jupyterlab extension of jupyterhub. The installation had the following output:
```
> npm pack /tmp/jupyterlab-fasta-master
npm WARN lifecycle jupyterlab-fasta@0.1.0~prepublish: cannot run in wd %s %s (wd=%s) jupyterlab-fas                                                                                                         ta@0.1.0 npm run build /tmp/jupyterlab-fasta-master
jupyterlab-fasta-0.1.0.tgz
> node node-version-check.js
> npm install

> canvas@1.6.6 install /usr/share/jupyter/lab/staging/node_modules/canvas
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.11.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/share/jupyter/lab/staging/nod                                                                                                         e_modules/canvas/.node-gyp"
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying                                                                                                          to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gy                                                                                                         p/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.10.0-514.26.2.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"                                                                                                          "rebuild"
gyp ERR! cwd /usr/share/jupyter/lab/staging/node_modules/canvas
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
@jupyterlab/application-top@0.10.2 /usr/share/jupyter/lab/staging
└─┬ jupyterlab-fasta@0.1.0
  └─┬ msa@1.0.3
    ├─┬ backbone-childs@1.0.3
    │ └── underscore@1.8.3
    ├─┬ backbone-thin@1.0.9
    │ ├── backbone-events-standalone@0.2.7
    │ └── backbone-extend-standalone@0.1.2
    ├── backbone-viewj@1.0.2
    ├─┬ bio.io@1.0.6
    │ ├── vow@0.4.16
    │ └─┬ xmldoc@0.5.1
    │   └── sax@1.1.6
    ├── biojs-events@0.0.4
    ├── biojs-model@0.0.2
    ├── biojs-vis-seqlogo@0.0.14
    ├── blueimp_canvastoblob@1.0.0
    ├── browser-saveas@1.0.1
    ├── dom-helper@1.0.0
    ├── jbone@1.2.0
    ├── koala-js@1.0.7
    ├── linear-scale@0.0.1
    ├── menu-builder@0.0.7
    ├── mouse-pos@1.0.3
    ├── msa-colorschemes@1.0.10
    ├── stat.seqs@0.1.21
    └─┬ xhr@2.4.0
      ├─┬ global@4.3.2
      │ ├─┬ min-document@2.19.0
      │ │ └── dom-walk@0.1.1
      │ └── process@0.5.2
      ├── is-function@1.0.1
      └─┬ parse-headers@2.0.1
        ├── for-each@0.3.2
        └── trim@0.0.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules                                                                                                         /fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os"                                                                                                         :"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.6 (node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.6 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> npm run build

> @jupyterlab/application-top@0.10.2 build /usr/share/jupyter/lab/staging
> webpack

Hash: fb4ebd3f170d0f8fe498
Version: webpack 2.7.0
Time: 8354ms
                                 Asset     Size  Chunks                    Chunk Names
  674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]
af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]
 fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]
  b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]
  912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]  [big]
                           0.bundle.js   893 kB       0  [emitted]  [big]
                        main.bundle.js  6.88 MB       1  [emitted]  [big]  main
                       0.bundle.js.map  1.08 MB       0  [emitted]
                    main.bundle.js.map  8.26 MB       1  [emitted]         main
  [26] ./~/@jupyterlab/application/lib/index.js 5.48 kB {1} [built]
 [439] ./~/@jupyterlab/application-extension/lib/index.js 6.12 kB {1} [optional] [built]
 [455] ./~/@jupyterlab/notebook-extension/lib/index.js 38.8 kB {1} [optional] [built]
 [457] ./~/@jupyterlab/running-extension/lib/index.js 1.67 kB {1} [optional] [built]
 [458] ./~/@jupyterlab/settingeditor-extension/lib/index.js 2.63 kB {1} [optional] [built]
 [459] ./~/@jupyterlab/shortcuts-extension/lib/index.js 3.7 kB {1} [optional] [built]
 [460] ./~/@jupyterlab/tabmanager-extension/lib/index.js 1.76 kB {1} [optional] [built]
 [461] ./~/@jupyterlab/terminal-extension/lib/index.js 7.29 kB {1} [optional] [built]
 [462] ./~/@jupyterlab/theme-dark-extension/lib/index.js 766 bytes {1} [optional] [built]
 [463] ./~/@jupyterlab/theme-light-extension/lib/index.js 770 bytes {1} [optional] [built]
 [464] ./~/@jupyterlab/tooltip-extension/lib/index.js 5.57 kB {1} [optional] [built]
 [465] ./~/@jupyterlab/vega2-extension/lib/index.js 6.13 kB {1} [optional] [built]
 [466] ./~/es6-promise/auto.js 179 bytes {1} [built]
 [467] ./~/font-awesome/css/font-awesome.min.css 892 bytes {1} [built]
 [481] ./build/index.out.js 8.56 kB {1} [built]
    + 1124 hidden modules

WARNING in ./build/index.out.js
Module not found: Error: Can't resolve 'jupyterlab-fasta/' in '/usr/share/jupyter/lab/staging/build                                                                                                         '
 @ ./build/index.out.js 43:32-60
```

When I check `jupyter labextension list` jupyterlab-fasta@0.1.0 is enabled and ok

**Comment by danpf** [comment]
repo deprecated: closing
